export const ALL_BOOKS_REQUEST = 'ALL_BOOKS_REQUEST'
export const ALL_BOOKS_SUCCESS = 'ALL_BOOKS_SUCCESS'
export const ALL_BOOKS_FAIL = 'ALL_BOOKS_FAIL'

export const BOOK_REQUEST = 'BOOK_REQUEST'
export const BOOK_SUCCESS = 'BOOK_SUCCESS'
export const BOOK_FAIL = 'BOOK_FAIL'

export const ADMIN_BOOKS_REQUEST = 'ADMIN_BOOKS_REQUEST'
export const ADMIN_BOOKS_SUCCESS = 'ADMIN_BOOKS_SUCCESS'
export const ADMIN_BOOKS_FAIL = 'ADMIN_BOOKS_FAIL'

export const NEW_BOOK_REQUEST = 'NEW_BOOK_REQUEST'
export const NEW_BOOK_SUCCESS = 'NEW_BOOK_SUCCESS'
export const NEW_BOOK_FAIL = 'ADMIN_BOOK_FAIL'
export const NEW_BOOK_RESET = 'ADMIN_BOOK_RESET'

export const DELETE_BOOK_REQUEST = 'DELETE_BOOK_REQUEST'
export const DELETE_BOOK_SUCCESS = 'DELETE_BOOK_SUCCESS'
export const DELETE_BOOK_FAIL = 'ADMIN_BOOK_FAIL'
export const DELETE_BOOK_RESET = 'ADMIN_BOOK_RESET'

export const CLEAR_ERRORS= 'CLEAR_ERRORS'